proton = {
    "name": "proton",
    "boson": False,
    "fermion": True,
    "baryon": True,
    "quark": False,
    "meson": False,
    "lepton": False,
    "hadron": True,
    "charge": "1",
    "mass": "938.27208816(29) MeV",
    "spin": "1/2+",
    "isospin": "1/2",
    "lifetime": "stable",
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": "uud",
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1",
    "strangeness": "0",
    "charm": "0"
}

up = {
    "name": "up-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "hadron": False,
    "charge": "2/3",
    "mass": "2.16(+49-26) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "0",
    "color charged": True,
    "note": "lightest quark",
    "decays into": "stable or down + e+ + nue"
}

down = {
    "name": "down-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "hadron": False,
    "charge": "-1/3",
    "mass": "4.67(+48-17) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "0",
    "color charged": True,
    "decays ino": "stable or up + e- + anti-nue"
}

electron = {
    "name": "electron",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "hadron": False,
    "charge": "-1",
    "mass": "510.99895000(15) keV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "1",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
    "note": "lightest lepton"
}

nue = {
    "name": "electron neutrino",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "hadron": False,
    "charge": "0",
    "mass": "< 1 eV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "1",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
}

charm = {
    "name": "charm-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "hadron": False,
    "charge": "2/3",
    "mass": "1.27(2) GeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "1",
    "color charged": True,
    "decays into": "s (~95 %), d (~5 %)"
}

strange = {
    "name": "strange-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "hadron": False,
    "charge": "-1/3",
    "mass": "93(+11-5) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "1",
    "charm": "0",
    "color charged": True,
    "decays into": "up"
}

muon = {
    "name": "muon",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "hadron": False,
    "charge": "-1",
    "mass": "105.6583745(24) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "2.1969811(22)e-6 s",
    "interaction": "weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "0",
    "muon number": "1",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
    "decays into": "e- + anti-nue + num"
}

num = {
    "name": "muon neutrino",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "hadron": False,
    "charge": "0",
    "mass": "< 0.17 MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "0",
    "muon number": "1",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
}

top = {
    "name": "top-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "hadron": False,
    "charge": "2/3",
    "mass": "172.76(30) GeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "0",
    "color charged": True,
    "decays into": "b (~99.8 %), s (~0.17 %), d (~0.007 %)"
}

bottom = {
    "name": "bottom-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "hadron": False,
    "charge": "-1/3",
    "mass": "4.18(+03-02)",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "0",
    "color charged": True,
    "decays into": "charm, up"
}

tau = {
    "name": "tau",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "hadron": False,
    "charge": "-1",
    "mass": "1776.86(12) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "290.3(5)e-15 s",
    "interaction": "weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "1",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
    "decays into": "charged pion + neutral poin + tau neutrino (~25.49 %), charged pion + tau neutrino (~10.82 %), charged pion + two neutral pions +tau neutrino (~9.26 %), three charged pion + tau neutrino (~8.99 %), three chared pions + neutral pion + tau neutrino (~2.74 %), three neutral pions + charged pion + tau neutrino (~1.04 %)",
    "note": "only lepton which can decay in hadrons"
}

nut = {
    "name": "tau neutrino",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "hadron": False,
    "charge": "0",
    "mass": "< 18.2 MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "1",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
}
