proton = {
    "name": "proton",
    "boson": False,
    "fermion": True,
    "baryon": True,
    "quark": False,
    "meson": False,
    "lepton": False,
    "charge": "1",
    "mass": "938.27208816(29) MeV",
    "spin": "1/2+",
    "isospin": "1/2",
    "lifetime": "stable",
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": "uud",
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1",
    "strangeness": "0",
    "charm": "0"
}

up = {
    "name": "up-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "charge": "2/3",
    "mass": "2.16(+49-26) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "0",
    "color charged": True,
    "note": "lightest quark",
    "decays into": "stable or down + e+ + nue"
}

down = {
    "name": "down-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "charge": "-1/3",
    "mass": "4.67(+48-17) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "0",
    "color charged": True,
    "decays ino": "stable or up + e- + anti-nue"
}

electron = {
    "name": "electron",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "charge": "-1",
    "mass": "510.99895000(15) keV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "1",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
    "note": "lightest lepton"
}

nue = {
    "name": "electron neutrino",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "charge": "0",
    "mass": "< 1 eV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "1",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
}

charm = {
    "name": "charm-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "charge": "2/3",
    "mass": "1.27(2) GeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "0",
    "charm": "1",
    "color charged": True,
    "decays into": "s (~95 %), d (~5 %)"
}

strange = {
    "name": "strange-quark",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": True,
    "meson": False,
    "lepton": False,
    "charge": "-1/3",
    "mass": "93(+11-5) MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": False,
    "interaction": "strong, weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "0",
    "electron number": "0",
    "muon number": "0",
    "tau numer": "0",
    "baryon numer": "1/3",
    "strangeness": "1",
    "charm": "0",
    "color charged": True,
    "decays into": "up"
}

muon = {
    "name": "muon",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "charge": "-1",
    "mass": "105.6583745(24)",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "2.1969811(22)e-6 s",
    "interaction": "weak, electromagnetism, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "0",
    "muon number": "1",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
    "decays into": "e- + anti-nue + num"
}

num = {
    "name": "muon neutrino",
    "boson": False,
    "fermion": True,
    "baryon": False,
    "quark": False,
    "meson": False,
    "lepton": True,
    "charge": "0",
    "mass": "< 0.17 MeV",
    "spin": "1/2",
    "isospin": False,
    "lifetime": "stable",
    "interaction": "weak, gravitation",
    "composition": False,
    "lepton number": "1",
    "electron number": "0",
    "muon number": "1",
    "tau numer": "0",
    "baryon numer": "0",
    "strangeness": "0",
    "charm": "0",
    "color charged": False,
}
